server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##POSTRES
    password: 1234567
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    org:
      hibernate:
        dialect:
          Oracle10gDialect: org.hibernate.dialect.Oracle10gDialect

cloudinary:
  cloud-name: dbqfw5na3
  api-key: 138684441112593
  api-secret: nLP8ck5j7YYio80tR2ov4Pysu-s


